# Generated by Django 2.1.7 on 2019-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
