# Generated by Django 2.1.7 on 2019-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190308_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['-pub_date']},
        ),
    ]
